server:
  port: 8071

spring:
  application:
    name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: onetwo12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8858    # Sentinel控制台地址（已改为8858端口）
        port: 8721                   # Sentinel客户端与Dashboard通信端口（用户服务:8721）
      web-context-unify: false       # 关闭上下文合并，支持链路限流
